### PR TITLE
remove main.convert import error

### PR DESCRIPTION
**Pull request by pragasitcha**
From #11 

Remove  import error

### CODE REVIEW

**Comment by pragasitcha** [comment]
@itsamam  @nathamETDA  Please review this PR

**Comment by nathamETDA** [comment]
Please provide more PR information, why this class causes error, is there any source code impact?
and test result.

**Comment by pragasitcha** [comment]
@nathamETDA 

previous version of source code imported non existing class which lead to project error 
by removing this class takes no impact to source code

test result 

image

image

**Comment by nathamETDA** [comment]
@pragasitcha 
lgtm

**Pull request merged**
